image: ubuntu:latest

before_script:

stages:
  - deploy
  - test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "Plugins"'

analyze:
  stage: test
  script:
    - apt update
    - apt install -y llvm libopenmpi-dev clang 
    - export LLVM_INCLUDE_PATH=$(llvm-config --includedir)
    - find src selector -name "*.cpp" -exec clang --analyze -I$LLVM_INCLUDE_PATH -Iqdmi/ {} \;

execute:
  stage: test
  script:
    - apt update
    - apt install -y cmake llvm libopenmpi-dev g++
    - export CMAKE_PREFIX_PATH=$(llvm-config --libdir)/cmake/llvm
    # ...
    - cd qdmi
    - mkdir build
    - cd build
    - cmake ..
    - make
    - echo QDMI built successfully
    # ...
    - cd ../../selector
    - mkdir build
    - cd build
    - cmake -DCUSTOM_EXECUTABLE_NAME=qselectorrunner_d ..
    - cmake --build .
    - echo Selector Runner built successfully
    - cd ../../tests
    # ...
    - mpic++ -std=c++14 test.cpp -o test
    - echo Test built successfully
    # ...
    - cd ..
    - mkdir build
    - cd build
    - cmake -DCUSTOM_EXECUTABLE_NAME=qpassrunner_d -DCUSTOM_QDMI_PATH=qdmi ..
    - cmake --build .
    - echo Pass Runner built successfully
    - make install
    - echo Pass Runner installed successfully
    # ...
    - qpassrunner_d screen &
    - sleep 1
    - cd ../selector/build/
    - ./qselectorrunner_d &
    - sleep 1
    - ../../tests/test

