image: ubuntu:latest

before_script:

stages:
  - deploy
  - test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "NoSockets"'

analyze:
  stage: test
  script:
    - apt update
    - apt install -y llvm libopenmpi-dev clang 
    - export LLVM_INCLUDE_PATH=$(llvm-config --includedir)
    - find src -name "*.cpp" -exec clang --analyze -I$LLVM_INCLUDE_PATH -Iqdmi/ {} \;

execute:
  stage: test
  script:
    - apt update
    - apt install -y cmake llvm rabbitmq-server g++ curl
    - curl -LO https://github.com/alanxz/rabbitmq-c/archive/refs/tags/v0.13.0.tar.gz
    - tar -xf v0.13.0.tar.gz
    - cd rabbitmq-c-0.13.0/
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DENABLE_SSL_SUPPORT=OFF ..
    - sudo cmake --build . --target install
    - sudo ldconfig
    - cd ../..
    - rm -rf rabbitmq-c-0.13.0/
    # ...
    - cd qdmi
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ../..
    - echo QDMI built successfully
    # ...
    - mkdir build
    - cd build
    - export CMAKE_PREFIX_PATH=$(llvm-config --libdir)/cmake/llvm
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME -DCUSTOM_QDMI_PATH=qdmi ..
    - cmake --build .
    - echo QRM built successfully
    # ...
    - cd tests
    - g++ test.cpp ../src/connection_handling.cpp -o test -lrabbitmq
    - echo Test built successfully
    - cd ..
    # ...
    - cd build
    - ./daemon_d screen &
    - sleep 1
    - ../tests/test

