image: ubuntu:latest

variables:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
 #AMQP_URL: 'amqp://guest:guest@rabbitmq:5672'

services:
 #- rabbitmq:latest
  - name: rabbitmq
    alias: rabbitmq #localhost

before_script:

stages:
  - deploy
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/src/pass_runner
    - build/src/pass_runner/passes
    - build/src/selector_runner
    - build/src/selector_runner/selectors
    - build/src/scheduler_runner
    - build/src/scheduler_runner/schedulers

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "NoSockets"'

analyze:
  stage: test
  script:
    - apt update
    - apt install -y llvm libopenmpi-dev clang 
    - export LLVM_INCLUDE_PATH=$(llvm-config --includedir)
    - find src -name "*.cpp" -exec clang --analyze -I$LLVM_INCLUDE_PATH -Iqdmi/ {} \;

execute:
  stage: test
  script:
    - apt update
   #- apt install -y cmake llvm g++
    - apt install -y cmake llvm rabbitmq-server g++ curl
    - curl -LO https://github.com/alanxz/rabbitmq-c/archive/refs/tags/v0.13.0.tar.gz
    - tar -xf v0.13.0.tar.gz
    - cd rabbitmq-c-0.13.0/
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DENABLE_SSL_SUPPORT=OFF ..
    - cmake --build . --target install
    - ldconfig
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - cd ../..
    - rm -rf rabbitmq-c-0.13.0/
   # ...
    - cd qdmi
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ../..
    - echo QDMI built successfully
    # ...
    - mkdir build
    - cd build
    - export CMAKE_PREFIX_PATH=$(llvm-config --libdir)/cmake/llvm
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME -DCUSTOM_QDMI_PATH=qdmi ..
    - cmake --build .
    - cd ..
    - echo QRM built successfully
    # ...
    - cd tests
    - g++ test.cpp ../src/connection_handling.cpp -o test -lrabbitmq
    - echo Test built successfully
    - cd ..
    # ...
    - cd build
    - ./daemon_d screen
    - sleep 1
    - ../tests/test
  artifacts:
    paths:
      - build/src/pass_runner/libPassRunner.so
      - build/src/pass_runner/passes/*.so
      - build/src/selector_runner/libSelectorRunner.so
      - build/src/selector_runner/selectors/*.so
      - build/src/scheduler_runner/libSchedulerRunner.so
      - build/src/scheduler_runner/schedulers/*.so
