image: ubuntu:latest

before_script:

stages:
  - deploy
  - test

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "NoSockets"'

analyze:
  stage: test
  script:
    - apt update
    - apt install -y llvm libopenmpi-dev clang 
    - export LLVM_INCLUDE_PATH=$(llvm-config --includedir)
    - find src -name "*.cpp" -exec clang --analyze -I$LLVM_INCLUDE_PATH -Iqdmi/ {} \;

execute:
  stage: test
  script:
    - apt update
    - apt install -y cmake llvm libopenmpi-dev g++
    - export CMAKE_PREFIX_PATH=$(llvm-config --libdir)/cmake/llvm
    # ...
    - cd qdmi
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ../..
    - echo QDMI built successfully
    # ...
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME -DCUSTOM_QDMI_PATH=qdmi ..
    - cmake --build .
    - echo Pass Runner built successfully
    # ...
    - cd tests
    - g++ test.cpp ../src/connection_handling.cpp -o test -lrabbitmq
    - echo Test built successfully
    - cd ..
    # ...
    - cd build
    - ./daemon_d screen &
    - sleep 1
    - ../tests/test

